# Generated by Django 6.0.2 on 2026-03-27 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_add_client_uuid'),
        ('timesheets', '0002_rename_todo_timesheetentry_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='', help_text='Description (saved to category)')),
                ('status', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='backlog', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('suggested_start_time', models.DateTimeField(blank=True, help_text='Suggested start time from slot finder (used for calendar sync)', null=True)),
                ('calendar_start_time', models.DateTimeField(blank=True, help_text='Event start time from Google Calendar (read-only, synced from calendar)', null=True)),
                ('calendar_end_time', models.DateTimeField(blank=True, help_text='Event end time from Google Calendar (read-only, synced from calendar)', null=True)),
                ('google_calendar_event_id', models.CharField(blank=True, help_text='Google Calendar event ID (to prevent duplicates)', max_length=255, null=True)),
                ('calendar_uuid', models.UUIDField(blank=True, default=uuid.uuid4, help_text='Unique identifier synced to Google Calendar for robust tracking', null=True)),
                ('synced_to_calendar', models.BooleanField(default=False, help_text='Marked as synced to Google Calendar')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours to complete this task', max_digits=6, null=True)),
                ('google_calendar_etag', models.CharField(blank=True, help_text='eTag for conflict detection with Google Calendar', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time this event was synced with Google Calendar', null=True)),
                ('last_synced_from', models.CharField(blank=True, choices=[('app', 'App'), ('calendar', 'Calendar')], help_text='Which system was the last source of truth', max_length=10)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed')], default='pending', help_text='Current sync status with Google Calendar', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Work category for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='timesheets.workcategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_direction', models.CharField(choices=[('push', 'App → Calendar'), ('pull', 'Calendar → App')], help_text='Direction of sync', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('synced_fields', models.JSONField(default=list, help_text='List of fields that were synced')),
                ('changes', models.JSONField(default=dict, help_text='Old and new values for each field')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sync failed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Sync Log',
                'verbose_name_plural': 'Event Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Calendar Credential',
                'verbose_name_plural': 'Google Calendar Credentials',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'google_calendar_event_id'], name='events_even_user_id_9cc548_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'sync_status'], name='events_even_user_id_927fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['last_synced_at'], name='events_even_last_sy_42731b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsynclog',
            index=models.Index(fields=['event', '-created_at'], name='events_even_event_i_b9520f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsynclog',
            index=models.Index(fields=['status', '-created_at'], name='events_even_status_08c443_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='googlecalendarcredential',
            unique_together={('user',)},
        ),
    ]
