# Generated by Django 6.0.2 on 2026-03-08 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'indexes': [models.Index(fields=['user', 'google_calendar_event_id'], name='events_even_user_id_a1b2c3_idx'), models.Index(fields=['user', 'sync_status'], name='events_even_user_id_d4e5f6_idx'), models.Index(fields=['last_synced_at'], name='events_even_last_sy_g7h8i9_idx')], 'ordering': ['-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='google_calendar_etag',
            field=models.CharField(blank=True, help_text='eTag for conflict detection with Google Calendar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this event was synced with Google Calendar', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='last_synced_from',
            field=models.CharField(blank=True, choices=[('app', 'App'), ('calendar', 'Calendar')], help_text='Which system was the last source of truth', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending Sync'), ('synced', 'Synced'), ('failed', 'Sync Failed')], default='pending', help_text='Current sync status with Google Calendar', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='googlecalendarcredential',
            options={'verbose_name': 'Google Calendar Credential', 'verbose_name_plural': 'Google Calendar Credentials'},
        ),
        migrations.CreateModel(
            name='EventSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_direction', models.CharField(choices=[('push', 'App → Calendar'), ('pull', 'Calendar → App')], help_text='Direction of sync', max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], default='success', max_length=20)),
                ('synced_fields', models.JSONField(default=list, help_text='List of fields that were synced')),
                ('changes', models.JSONField(default=dict, help_text='Old and new values for each field')),
                ('error_message', models.TextField(blank=True, help_text='Error message if sync failed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Sync Log',
                'verbose_name_plural': 'Event Sync Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', '-created_at'], name='events_even_event_i_b9520f_idx'), models.Index(fields=['status', '-created_at'], name='events_even_status_08c443_idx')],
            },
        ),
    ]
