# Generated by Django 6.0.2 on 2026-03-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_start_time',
            field=models.DateTimeField(blank=True, help_text='Event start time from Google Calendar (read-only, synced from calendar)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='calendar_end_time',
            field=models.DateTimeField(blank=True, help_text='Event end time from Google Calendar (read-only, synced from calendar)', null=True),
        ),
    ]
