# Generated by Django 6.0.2 on 2026-03-08 10:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_calendar_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True, blank=True, help_text='Unique identifier synced to Google Calendar for robust tracking'),
        ),
    ]
