# Generated by Django 6.0 on 2025-12-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_create_default_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='VAT/Tax Number'),
        ),
    ]
