# Generated by Django 6.0.1 on 2026-02-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='show_onboarding_tips',
            field=models.BooleanField(default=True),
        ),
    ]
