# Generated by Django 6.0 on 2025-12-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_vat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Income Tax Number'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vendor Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='VAT Number'),
        ),
    ]
