# Generated by Django 6.0.1 on 2026-02-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_show_onboarding_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(default='R', help_text='e.g. R, $, €', max_length=3),
        ),
    ]
