# Generated by Django 6.0 on 2025-12-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Set to 0 for No VAT', max_digits=5),
        ),
    ]
