# Generated by Django 6.0.1 on 2026-02-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invoice_footer',
            field=models.TextField(blank=True, default='Please use the invoice number as the payment reference.', help_text='Footer notes for invoices.'),
        ),
    ]
