# Generated by Django 6.0 on 2026-01-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_business_email_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_vat_registered',
            field=models.BooleanField(default=False),
        ),
    ]
