# Generated by Django 6.0.1 on 2026-02-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_added_by_user_is_ops'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='initial_setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
