# Generated by Django 6.0 on 2026-01-07 08:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_is_vat_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='VAT rate for VAT regi', max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
