# Generated by Django 6.0.1 on 2026-02-13 14:04

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_initial_setup_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
