# Generated by Django 6.0 on 2026-01-18 08:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_vat_rate_alter_userprofile_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tax_rate',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5),
        ),
    ]
