# Generated by Django 6.0 on 2026-01-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_userprofile_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text='Your monthly revenue goal (e.g., 50000)', max_digits=10),
        ),
    ]
