# Generated by Django 6.0 on 2026-01-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_monthly_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='swift_bic',
            field=models.CharField(blank=True, max_length=20, verbose_name='SWIFT/BIC Code'),
        ),
    ]
