# Generated by Django 6.0.1 on 2026-02-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_name',
            field=models.CharField(blank=True, help_text='Contact person for email preferences.', max_length=255),
        ),
    ]
