# Generated by Django 6.0.2 on 2026-02-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='audit_enabled',
            field=models.BooleanField(default=True, help_text='Enable anomaly detection for invoices'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='audit_sensitivity',
            field=models.CharField(choices=[('STRICT', 'Strict (1.5σ) - Catches ~6.7% outliers'), ('MEDIUM', 'Medium (2σ) - Catches ~2.3% outliers'), ('LENIENT', 'Lenient (2.5σ) - Catches ~1.2% outliers')], default='MEDIUM', help_text='How aggressive should anomaly detection be?', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='audit_triggers',
            field=models.JSONField(blank=True, default=dict, help_text='Which audit checks are enabled'),
        ),
    ]
