# Generated by Django 6.0.2 on 2026-02-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_audit_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='audit_enabled',
            field=models.BooleanField(default=False, help_text='Enable anomaly detection for invoices'),
        ),
    ]
