# Generated by Django 6.0.2 on 2026-02-24 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_userprofile_audit_enabled'),
        ('invoices', '0012_payment_credit_applied_alter_payment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks_run', models.JSONField(help_text='Which audit checks were executed')),
                ('flags_raised', models.JSONField(default=list, help_text='List of issues detected')),
                ('comparison_invoices_count', models.IntegerField(default=0, help_text='How many historical invoices were compared')),
                ('is_flagged', models.BooleanField(default=False)),
                ('was_approved', models.BooleanField(default=False, help_text='User approved despite flag (for learning)')),
                ('approval_reason', models.TextField(blank=True, help_text='Why user approved a flagged invoice')),
                ('comparison_mean', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('comparison_stddev', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('comparison_cv', models.DecimalField(decimal_places=3, default=0, help_text='Coefficient of Variation', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit_decision', to='invoices.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit History',
                'verbose_name_plural': 'Audit Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
