# Generated by Django 6.0.2 on 2026-02-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_audithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audithistory',
            name='comparison_cv',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Coefficient of Variation', max_digits=5, null=True),
        ),
    ]
