# Generated by Django 6.0.2 on 2026-03-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_audithistory_comparison_cv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpsManager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_ops',
        ),
    ]
