# Generated by Django 6.0.2 on 2026-03-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_ops_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tax_year_type',
            field=models.CharField(choices=[('ZA', 'South Africa (Mar 1 - Feb 28)'), ('US', 'United States (Jan 1 - Dec 31)'), ('UK', 'United Kingdom (Apr 1 - Mar 31)'), ('AU', 'Australia (Jul 1 - Jun 30)'), ('CA', 'Canada (Jan 1 - Dec 31)'), ('NZ', 'New Zealand (Apr 1 - Mar 31)')], default='ZA', help_text='Your financial/tax year start date', max_length=2),
        ),
    ]
