# Generated by Django 6.0.2 on 2026-03-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile_tax_year_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='annual_revenue_target',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Your annual revenue goal (optional). If blank, uses monthly_target × 12', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='threshold_crossed',
            field=models.BooleanField(default=False, help_text='Flag set when annual revenue exceeds VAT/GST threshold'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vat_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Revenue threshold for VAT/GST registration (e.g., 30000). Auto-set based on tax_year_type.', max_digits=12, null=True),
        ),
    ]
