# Generated by Django 6.0.2 on 2026-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userprofile_annual_revenue_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Reply-to email for invoice emails. Clients can reply directly to this address.', max_length=254),
        ),
    ]
