# Generated by Django 6.0.2 on 2026-03-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_userprofile_business_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='break_minutes',
            field=models.IntegerField(default=15, help_text='Buffer time between appointments (in minutes)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_days',
            field=models.JSONField(default=list, help_text='Days you work (0=Monday, 6=Sunday). Default is Mon-Fri'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_end_time',
            field=models.TimeField(default='17:00', help_text='End of working day (default 5:00 PM)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_start_time',
            field=models.TimeField(default='09:00', help_text='Start of working day (default 9:00 AM)'),
        ),
    ]
