# Generated by Django 6.0.2 on 2026-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprofile_break_minutes_userprofile_work_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enabled_plugins',
            field=models.JSONField(blank=True, default=list, help_text="List of app labels for enabled plugins (e.g., ['items', 'timesheets'])"),
        ),
    ]
