# Generated by Django 6.0.1 on 2026-02-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingpolicy',
            name='special_rule',
            field=models.CharField(choices=[('NONE', 'Exact Date Only'), ('WORK', 'First Working Day')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='billingpolicy',
            name='run_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
