# Generated by Django 6.0.1 on 2026-02-04 10:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_schedule', '0002_billingpolicy_special_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingpolicy',
            options={'verbose_name': 'Billing Policy', 'verbose_name_plural': 'Billing Policies'},
        ),
        migrations.AlterUniqueTogether(
            name='billingpolicy',
            unique_together={('user', 'run_day', 'special_rule')},
        ),
    ]
