# Generated by Django 6.0.2 on 2026-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_schedule', '0003_alter_billingpolicy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingpolicy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to stop using this policy temporarily'),
        ),
        migrations.AlterField(
            model_name='billingpolicy',
            name='name',
            field=models.CharField(help_text="E.g., 'Monthly Billing - 1st of Month' or 'Monthly Billing - 15th of Month'", max_length=100),
        ),
        migrations.AlterField(
            model_name='billingpolicy',
            name='run_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Set to specific day (1-31) for 'Exact Date Only'. Leave blank for 'First Working Day'. Items added before this day will bill on this day next month.", null=True),
        ),
        migrations.AlterField(
            model_name='billingpolicy',
            name='special_rule',
            field=models.CharField(choices=[('NONE', 'Exact Date Only'), ('WORK', 'First Working Day')], default='NONE', help_text='Choose how often this policy runs: exact date vs. first working day', max_length=10),
        ),
    ]
