# Generated by Django 6.0 on 2025-12-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending / Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Void / Cancelled')], default='DRAFT', max_length=10),
        ),
    ]
