# Generated by Django 6.0 on 2025-12-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_type',
            field=models.CharField(choices=[('product', 'Product-based (Qty/Price)'), ('service', 'Service-based (Hours/Rate)')], default='service', max_length=10),
        ),
    ]
