# Generated by Django 6.0.1 on 2026-02-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_email_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
