# Generated by Django 6.0.1 on 2026-02-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_emailed_at_invoice_is_emailed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes or terms for the invoice.'),
        ),
    ]
