# Generated by Django 6.0 on 2025-12-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_billing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_exempt',
            field=models.BooleanField(default=False, help_text='Check if this invoice should not include VAT'),
        ),
    ]
