# Generated by Django 6.0.1 on 2026-02-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, default='Please use the invoice number as the payment reference.', help_text='Notes or terms for the invoice.'),
        ),
    ]
