# Generated by Django 6.0 on 2025-12-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_tax_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
    ]
