# Generated by Django 6.0 on 2026-01-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoiceitem_is_taxable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_exempt',
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_mode',
            field=models.CharField(choices=[('NONE', 'No VAT Charged (Non-Vendor)'), ('FULL', 'VAT on Whole Invoice'), ('MIXED', 'Item-by-Item VAT (Mixed/Zero-Rated)')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_type',
            field=models.CharField(choices=[('PRODUCT', 'Product-based (Qty/Price)'), ('SERVICE', 'Service-based (Hours/Rate)')], default='SERVICE', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending / Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10),
        ),
    ]
