# Generated by Django 6.0.1 on 2026-02-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='notes',
        ),
    ]
