# Generated by Django 6.0 on 2026-01-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_invoice_tax_exempt_invoice_tax_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_type',
            field=models.CharField(choices=[('PRODUCT', 'Product-based'), ('SERVICE', 'Service-based')], default='SERVICE', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='latex_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_mode',
            field=models.CharField(choices=[('NONE', 'Exempt (No VAT)'), ('FULL', 'VAT on Whole Invoice'), ('MIXED', 'Mixed (Item-by-Item)')], default='NONE', max_length=10),
        ),
    ]
