# Generated by Django 6.0 on 2026-01-03 08:44

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_code_client_tax_number_and_more'),
        ('invoices', '0007_invoice_subtotal_amount_invoice_tax_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_issued', '-id']},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='latex_content',
            field=models.TextField(blank=True, help_text='The raw LaTeX source used to generate the PDF.'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('user', 'number'), name='unique_invoice_per_tenant'),
        ),
    ]
