# Generated by Django 6.0.1 on 2026-02-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoiceemailstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attach_timesheet_to_email',
            field=models.BooleanField(default=False, help_text='Attach timesheet report PDF to invoice email if created from timesheet.'),
        ),
    ]
