# Generated by Django 6.0.1 on 2026-02-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoiceemailtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceemailtracking',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
