# Generated by Django 6.0.1 on 2026-02-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_attach_timesheet_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation', null=True),
        ),
    ]
