# Generated by Django 6.0.1 on 2026-02-23 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_unique_client_code_per_user'),
        ('invoices', '0009_invoice_cancellation_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('OVERPAYMENT', 'Overpayment'), ('ADJUSTMENT', 'Manual Adjustment'), ('CANCELLATION', 'Cancelled Invoice'), ('OTHER', 'Other')], default='ADJUSTMENT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Reason for credit note')),
                ('reference', models.CharField(blank=True, help_text='e.g., CN2026-001', max_length=100)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Remaining credit available to use', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='clients.client')),
                ('invoice', models.ForeignKey(blank=True, help_text='Original invoice if related to overpayment/cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='invoices.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date', '-created_at'],
            },
        ),
    ]
