# Generated by Django 6.0.1 on 2026-02-23 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_creditnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., SUMMER2026, LOYAL10', max_length=50)),
                ('discount_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage Discount')], default='FIXED', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Fixed amount or percentage (e.g., 10.00 for 10% or R500)', max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Coupon description for internal use')),
                ('max_uses', models.IntegerField(blank=True, help_text='Unlimited if blank', null=True)),
                ('current_uses', models.IntegerField(default=0, help_text='Number of times coupon has been used')),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, help_text='Null = no expiry', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'code')},
            },
        ),
    ]
