# Generated by Django 6.0.2 on 2026-02-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_payment_credit_applied_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_quote',
            field=models.BooleanField(db_index=True, default=False, help_text='If checked, this is a quote. Once accepted, can be converted to an invoice.'),
        ),
    ]
