# Generated by Django 6.0.2 on 2026-02-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_invoice_is_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='was_originally_quote',
            field=models.BooleanField(db_index=True, default=False, help_text='Tracks whether this invoice was originally created as a quote before being converted.'),
        ),
    ]
