# Generated by Django 6.0.2 on 2026-02-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_add_was_originally_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quote_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Tracks quote status: pending, accepted, or rejected.', max_length=20, null=True),
        ),
    ]
