# Generated by Django 6.0.2 on 2026-02-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_add_quote_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_mode',
        ),
        migrations.AlterField(
            model_name='taxpayment',
            name='reference',
            field=models.CharField(blank=True, help_text='e.g., VAT201 Period 2026/01. Leave blank for auto-generated reference.', max_length=100, null=True),
        ),
    ]
