# Generated by Django 6.0.2 on 2026-03-31 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_barcode'),
        ('recipes', '0002_ingredient_purchase_quantity_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_ingredients', to='inventory.inventoryitem'),
        ),
    ]
