# Generated by Django 6.0.1 on 2026-01-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_terms', models.PositiveIntegerField(default=14, help_text='Days until invoice is due')),
                ('default_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Standard rate used for new timesheet entries.', max_digits=10)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('vat_number', models.CharField(blank=True, max_length=50, verbose_name='VAT Number')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='TAX Number')),
                ('vendor_number', models.CharField(blank=True, max_length=50, verbose_name='Vendor Number')),
                ('client_code', models.CharField(blank=True, max_length=10)),
                ('weekly_target_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Target hours per week for this client.', max_digits=5)),
                ('monthly_target_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Target hours per month for this client.', max_digits=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
