# Generated by Django 6.0 on 2025-12-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='TAX Number'),
        ),
        migrations.AddField(
            model_name='client',
            name='vendor_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Vendor Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='VAT Number'),
        ),
    ]
