# Generated by Django 6.0 on 2026-01-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_client_code_client_tax_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Standard rate used for new timesheet entries.', max_digits=10),
        ),
    ]
