# Generated by Django 6.0.1 on 2026-01-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact Name'),
        ),
    ]
