# Generated by Django 6.0 on 2026-01-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_default_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_terms',
            field=models.PositiveIntegerField(default=14, help_text='Days until invoice is due'),
        ),
    ]
