# Generated by Django 6.0 on 2026-01-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='monthly_target_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Target hours per month for this client.', max_digits=6),
        ),
        migrations.AddField(
            model_name='client',
            name='weekly_target_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Target hours per week for this client.', max_digits=5),
        ),
    ]
