# Generated by Django 6.0.2 on 2026-03-06 07:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_unique_client_code_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for syncing with Google Contacts'),
        ),
    ]
