# Generated by Django 6.0.2 on 2026-04-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_add_client_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='external_id',
            field=models.CharField(blank=True, help_text='External system identifier (e.g., MealShare organisation ID for API integration)', max_length=255, null=True, unique=True),
        ),
    ]
