# Generated by Django 6.0.2 on 2026-02-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_billing_policy_serviceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_taxable',
        ),
    ]
