# Generated by Django 6.0.2 on 2026-03-05 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_schedule', '0004_alter_billingpolicy_is_active_and_more'),
        ('items', '0003_remove_item_is_taxable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='billing_policy',
            field=models.ForeignKey(blank=True, help_text='(OPTIONAL) Choose a policy for fixed billing dates (1st, 15th, first working day, etc). Leave BLANK for default: bills once per month on the same day each month.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_items', to='billing_schedule.billingpolicy'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='billing_policy',
            field=models.ForeignKey(blank=True, help_text='(OPTIONAL) Choose a policy for fixed billing dates. Leave BLANK for once per month (default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_items', to='billing_schedule.billingpolicy'),
        ),
    ]
