# Generated by Django 6.0.2 on 2026-04-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_billing_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_billed',
        ),
    ]
