# Generated by Django 6.0.2 on 2026-03-05 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_timesheetentry_todo'),
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Work category for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='timesheets.workcategory'),
        ),
    ]
