# Generated by Django 6.0.2 on 2026-03-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default selling price when billed', max_digits=10),
        ),
    ]
