# Generated by Django 6.0.2 on 2026-03-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_default_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='default_price',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
