# Generated by Django 6.0.2 on 2026-03-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventoryitem_default_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
