# Generated by Django 6.0.2 on 2026-03-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='integration_user_id_0d5d90_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='integration_user_id_be43ba_idx',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventSyncLog',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
