# Generated by Django 6.0.2 on 2026-03-28 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_remove_event_integration_user_id_0d5d90_idx_and_more'),
        ('inventory', '0001_initial'),
        ('items', '0004_alter_item_billing_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('auto_decrement', models.BooleanField(default=True, help_text='Automatically reduce stock when this item is billed')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='inventory.inventoryitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_links', to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item Inventory Link',
                'unique_together': {('item', 'inventory_item')},
            },
        ),
    ]
