# Generated by Django 6.0.2 on 2026-03-28 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_iteminventorylink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items_enabled', models.BooleanField(default=True, help_text='Billing items module')),
                ('inventory_enabled', models.BooleanField(default=False, help_text='Inventory linked items')),
                ('timesheets_enabled', models.BooleanField(default=False, help_text='Billable timesheets')),
                ('calendar_events_enabled', models.BooleanField(default=False, help_text='Google Calendar Sync')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration Setting',
                'verbose_name_plural': 'Integration Settings',
            },
        ),
    ]
