# Generated by Django 6.0.2 on 2026-03-28 11:57

from django.db import migrations
from django.conf import settings


def backfill_integration_settings(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    IntegrationSettings = apps.get_model('integrations', 'IntegrationSettings')
    
    for user in User.objects.all():
        IntegrationSettings.objects.get_or_create(
            user=user, 
            defaults={'inventory_enabled': True}
        )

class Migration(migrations.Migration):
    dependencies = [
        ('integrations', '0004_integrationsettings'),
    ]
    operations = [
        migrations.RunPython(backfill_integration_settings),
    ]