# Generated by Django 6.0.2 on 2026-03-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_integrationsettings'),
        ('integrations', '0005_backfill_settings'),
    ]

    operations = [
    ]
