# Generated by Django 6.0.2 on 2026-03-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_merge_0004_integrationsettings_0005_backfill_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='barcodes_enabled',
            field=models.BooleanField(default=False, help_text='Barcode generation and scanning'),
        ),
    ]
