# Generated by Django 6.0.2 on 2026-03-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_integrationsettings_barcodes_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='recipes_enabled',
            field=models.BooleanField(default=False, help_text='Recipe Costing'),
        ),
    ]
