# Generated by Django 6.0.2 on 2026-04-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_integrationsettings_recipes_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationsettings',
            name='recipes_enabled',
        ),
    ]
