# Generated by Django 6.0.2 on 2026-03-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='google_calendar_event_id',
        ),
    ]
