# Generated by Django 6.0 on 2026-01-03 18:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoice_options_alter_invoice_unique_together_and_more'),
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheetentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Timesheet Entries'},
        ),
        migrations.RemoveField(
            model_name='timesheetentry',
            name='linked_invoice',
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_timesheets', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
