# Generated by Django 6.0.1 on 2026-02-20 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_workcategory_created_at_workcategory_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='description',
        ),
    ]
