# Generated by Django 6.0.1 on 2026-02-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_remove_timesheetentry_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultWorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('metadata_schema', models.JSONField(blank=True, default=list, help_text='List of extra field names')),
            ],
        ),
    ]
