# Generated by Django 6.0.2 on 2026-03-05 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_defaultworkcategory'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_entries', to='events.event'),
        ),
    ]
