# Generated by Django 6.0 on 2026-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0004_alter_timesheetentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='unit_type',
            field=models.CharField(choices=[('HRS', 'Hours'), ('DAYS', 'Days'), ('MONTHS', 'Months'), ('UNITS', 'Units'), ('FIXED', 'Fixed Price')], default='HRS', max_length=10),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
