# Generated by Django 6.0 on 2026-01-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_timesheetentry_unit_type_alter_timesheetentry_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='unit_type',
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
