# Generated by Django 6.0.2 on 2026-03-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0005_timesheetentry_todo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheetentry',
            options={'ordering': ['-date', '-id'], 'verbose_name_plural': 'Timesheet Entries'},
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, db_index=True, help_text='Google Calendar event ID if imported from calendar', max_length=255, null=True),
        ),
    ]
