# Generated by Django 6.0.2 on 2026-04-04 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_size', models.DecimalField(decimal_places=2, help_text='e.g. 500 for 500g', max_digits=10)),
                ('unit_type', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('unit', 'Units')], default='g', max_length=20)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='larder.productmaster')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='larder.grocerystore')),
            ],
            options={
                'ordering': ['price'],
                'unique_together': {('product', 'store')},
            },
        ),
    ]
