# Generated by Django 6.0.2 on 2026-04-04 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larder', '0002_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshProduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('unit', models.CharField(default='kg', help_text='e.g., kg, bunch, piece', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fresh_produce', to='larder.grocerystore')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'supplier', 'category')},
            },
        ),
    ]
