# Generated by Django 6.0.2 on 2026-04-05 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larder', '0005_shoppinglistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipe',
            name='larder_reci_user_id_0be3b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='larder_reci_user_id_64402a_idx',
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1, help_text='Number of servings this recipe makes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.JSONField(blank=True, default=list, help_text="List of allergens: ['nuts', 'dairy', 'gluten', etc]. Empty = auto-derived from ingredients"),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['user', 'created_at'], name='larder_reci_user_id_bac234_idx'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_vegetarian',
        ),
    ]
